### ISSUE TITLE
Specify Timestamp instead of forced time.time()

### ISSUE THREAD

**Issue by Kayoku** [scarchik/opentsdb-py#7]
Hi,

First, thank you for your work.

You need to know that I'm not familiar with OpenTSDB, but anyway I need to make it compatible with my current project and I want to use your library for that. I have a problem with your way to handle timestamp in the `send` function.

```python3
def send(self, name: str, value, **tags) -> dict:
        tags.update(self.static_tags)
        if self.host_tag is True and 'host' not in tags:
            tags['host'] = socket.gethostname()

        self._validate_metric(name, value, tags)
        metric = dict(metric=name, timestamp=int(tags.pop('timestamp', time.time())), value=value, tags=tags)

        if not self._close_client.is_set():
            self._push_metric_to_queue(metric)

return metric
```

I can see that you are doing a "time.time()", **do you think there would be a way to make it configurable ?** 

Something like that:

```python3
def send(self, name: str, value, **tags, timestamp=time.time()) -> dict:
        tags.update(self.static_tags)
        if self.host_tag is True and 'host' not in tags:
            tags['host'] = socket.gethostname()

        self._validate_metric(name, value, tags)
        metric = dict(metric=name, timestamp=int(tags.pop('timestamp', timestamp)), value=value, tags=tags)

        if not self._close_client.is_set():
            self._push_metric_to_queue(metric)

return metric
```

And allow the user to specify the timestamp when using Gauge (for example)

```python3
tsdb.ACTIVE_USERS.set(12, timestamp=my_personal_timestamp)
```

Thank you !

**Comment by Kayoku** [comment]
Hi, I created a PR #8 related to this problem, don't hesitate to tell me if something bothers you!
@scarchik

**Comment by scarchik** [comment]
Hi @Kayoku, 
There is actually a way to specify your custom timestamp by using tags. 
You can see this in code: `int(tags.pop('timestamp', time.time()))`.
`time.time()` is a default way of getting timestamp in python, so I am don't understand why you need something else.

About your PR, it breaks compatibility with Prometheus library for me. I want to save some compatibility to switch between opentsdb and prometheus.

**Comment by Kayoku** [comment]
Aaaargh you're right, what a stupid misunderstanding :D !
Sorry for wasting your time, thanks.
